#!/bin/sh      
#      
# tomcat: Start/Stop/Restart tomcat      
#      
# chkconfig: 2345 80 20      
# description: Tomcat is a Java Servlet Container      
#      
# match these values to your environment:      
 
start() {      
   echo -n "Starting Tomcat: "      
   su - webuser -c "/usr/local/tomcat/bin/catalina.sh start"      
}      
  
stop() {      
  echo -n "Stopping Tomcat: "      
  su - webuser -c "/usr/local/tomcat/bin/catalina.sh stop"      
}      
  
# See how we were called.      
case "$1" in      
    start)      
      start      
	  ;;      
      
    stop)      
      stop      
      ;;      
      
    status)      
     ;;         
      
    restart)      
      stop      
      start      
      ;;      
      
    *)      
      echo "Usage: $0 {start  stop  restart}"      
      ;;      
  
esac      
  
exit $RETVAL
